
/*---------------------------------------------------------

	Developer's Notes:
	
	DO NOT EDIT THIS FILE.
	
---------------------------------------------------------*/

NARWHAL = {}
NARWHAL_FOLDER = GM.Folder:sub(11)

// Include shared files
include( 'includes_shd.lua' )

DeriveGamemode( NARWHAL_DERIVATIVE or "base" )

// We're gonna cheat and re-register the gamemode with your base of choice ;D
// What this means is you can port just about any gamemode to narwhal by changing just a few lines.
if NARWHAL_DERIVATIVE and NARWHAL_DERIVATIVE:lower() != "base" and NARWHAL_DERIVATIVE:lower() != NARWHAL_FOLDER then
	Msg( "Re-registering gamemode '"..NARWHAL_FOLDER.."' derived from '"..NARWHAL_DERIVATIVE.."'\n" )
	gamemode.Register( GM, NARWHAL_FOLDER, NARWHAL_DERIVATIVE )
	GM = gamemode.Get( NARWHAL_FOLDER )
end

IncludeNarwhalModules()
IncludeNarwhalThemes()

GM.Name 		= "Narwhal"
GM.Author 		= "Team GModCentral"
GM.Email 		= "team@gmodcentral.com"
GM.Website 		= "www.gmodcentral.com"
GM.TeamBased 	= false
GM.__IsNarwhalGamemode = true

function GM:IsNarwhalGamemode()
	return GAMEMODE.__IsNarwhalGamemode
end

/*---------------------------------------------------------
   Name: LoadModules
   Desc: This is called from Initialize. Load any modules that require some sort of instantiation at the beginning.
---------------------------------------------------------*/
function NARWHAL:LoadModules()
	--fill me in!
end

/*---------------------------------------------------------
   Name: LoadNetworkConfigurations
   Desc: Called internally to load custom network configurations.
---------------------------------------------------------*/
function NARWHAL:LoadNetworkConfigurations()
	-- NARWHAL:AddValidNetworkType( sType, sRef, sStore, funcCheck, funcSend, funcRead )
	-- Refer to network/network_shd.lua
end

/*---------------------------------------------------------
   Name: ForceTheme
   Desc: This sets a default theme for the gamemode.
---------------------------------------------------------*/
function NARWHAL:ForceTheme()
	return "Default"
end

/*---------------------------------------------------------
   Name: ThemeChanged
   Desc: Called when the theme is changed.
---------------------------------------------------------*/
function NARWHAL:ThemeChanged( oldTheme, newTheme )
	//if oldTheme == "Default" and newTheme == "myAwesomeTheme" then
	//	return false -- We don't want this awesome theme to be set! >:(
	//end
	return true
end

/*---------------------------------------------------------
   Name: EntityRemoved
   Desc: Called right before an entity is removed. Note that this
   isn't going to be totally reliable on the client since the client
   only knows about entities that it has had in its PVS.
---------------------------------------------------------*/
function GM:EntityRemoved( ent )
	//NARWHAL:RemoveEntityIndex( ent ) -- Remove all the NWVars from the cache for this entity
end

/*---------------------------------------------------------
   Name: Tick
   Desc: Like Think except called every tick on both client and server
---------------------------------------------------------*/
function GM:Tick()
end

/*---------------------------------------------------------
   Name: OnEntityCreated
   Desc: Called right after the Entity has been made visible to Lua
---------------------------------------------------------*/
function GM:OnEntityCreated( Ent )
end

