
/*---------------------------------------------------------

	Developer's Notes:
	
	DO NOT EDIT THIS FILE.
	
---------------------------------------------------------*/

// This is experimental.
NARWHAL_DERIVATIVE = NARWHAL_DERIVATIVE or "base"

print( "loaded narwhal", NARWHAL_DERIVATIVE )

// Include shared files
include( 'includes_shd.lua' )

DeriveGamemode( NARWHAL_DERIVATIVE )

// DO NOT EDIT THIS!!!!
if NARWHAL_DERIVATIVE and NARWHAL_DERIVATIVE:lower() != "base" and NARWHAL_DERIVATIVE:lower() != "narwhal" then
	gamemode.Register( GM, "Narwhal", NARWHAL_DERIVATIVE )
	GM = gamemode.Get( "Narwhal" )
end

GM.Name 		= "Narwhal Base"
GM.Author 		= "Team GModCentral"
GM.Email 		= "team@gmodcentral.com"
GM.Website 		= "www.gmodcentral.com"
GM.TeamBased 	= true

/*---------------------------------------------------------
   Name: LoadModules
   Desc: This is called from Initialize. Load any modules that require some sort of instantiation at the beginning.
---------------------------------------------------------*/
function NARWHAL:LoadModules()
	--fill me in!
end

/*---------------------------------------------------------
   Name: LoadNetworkConfigurations
   Desc: Called internally to load custom network configurations.
---------------------------------------------------------*/
function NARWHAL:LoadNetworkConfigurations()
	-- NARWHAL:AddValidNetworkType( sType, sRef, sStore, funcCheck, funcSend, funcRead )
	-- Refer to network/network_shd.lua
end

/*---------------------------------------------------------
   Name: ForceTheme
   Desc: This sets a default theme for the gamemode.
---------------------------------------------------------*/
function NARWHAL:ForceTheme()
	return "Default"
end

/*---------------------------------------------------------
   Name: ThemeChanged
   Desc: Called when the theme is changed.
---------------------------------------------------------*/
function NARWHAL:ThemeChanged( oldTheme, newTheme )
	//if oldTheme == "Default" and newTheme == "myAwesomeTheme" then
	//	return false -- We don't want this awesome theme to be set! >:(
	//end
	return true
end

/*---------------------------------------------------------
   Name: EntityRemoved
   Desc: Called right before an entity is removed. Note that this
   isn't going to be totally reliable on the client since the client
   only knows about entities that it has had in its PVS.
---------------------------------------------------------*/
function GM:EntityRemoved( ent )
	//NARWHAL:RemoveEntityIndex( ent ) -- Remove all the NWVars from the cache for this entity
end

/*---------------------------------------------------------
   Name: Tick
   Desc: Like Think except called every tick on both client and server
---------------------------------------------------------*/
function GM:Tick()
end

/*---------------------------------------------------------
   Name: OnEntityCreated
   Desc: Called right after the Entity has been made visible to Lua
---------------------------------------------------------*/
function GM:OnEntityCreated( Ent )
end

